### ISSUE TITLE
-w unknown in argument file

### ISSUE THREAD

**Issue by MisterY** [simonmichael/hledger#1028]
Using "time.hl" text file as
```
--file=time.ledger
-w100
```
and running `hledger @time.hl r`
results in
```
$ hl @time.hl r
hledger.exe: Unknown flag: -w (use -h to see usage)
```

A side note, I'm using a link `hl` which points to hledger.exe.

**Comment by simonmichael** [comment]
Thanks for the report. -w [must appear after](https://hledger.org/manual.html#command-options) the r, since it's specific to the register command. So `hledger r @time.hl` will work.

**Comment by simonmichael** [comment]
PS I'd be glad if someone removed that limitation, but be warned it's probably much harder than it sounds. Parsing options robustly is complicated, and whatever library we use to help also brings limitations.

Issues like this may be a reason why I don't use argument files much myself. For common/complicated commands I seem to prefer either bash aliases (`alias timereg="hledger -f time.timedot reg -w100"`) or Make rules. This particular option `-w` isn't one I script though, since I'll want it to vary depending on current window width. In fact using the window width is the default behaviour, I wonder why you're needing to specify it.

**Comment by MisterY** [comment]
> I wonder why you're needing to specify it.

I guess I need it on Windows. On my Linux box it uses the available width, which is a decent default.

> So hledger r @time.hl will work

Thanks! That's good enough.

**Comment by simonmichael** [comment]
> I guess I need it on Windows.

Ah, you're right; I wasn't able to support it there.

**Comment by MisterY** [comment]
I am, actually, also using MSysGit Bash on Windows but the behaviour is the same.
The best option on Windows would be to use the Windows Subsystem for Linux but due to internal policies this cannot install or run on the workstation. :(
