### ISSUE TITLE
Use regular expression capture groups in conditional rules in CSV import

### ISSUE THREAD

**Issue by alerque** [simonmichael/hledger#1061]
Yesterday I was trying to figure out how it import some poorly constructed CSV files. The CSV fields only had 4 fields, but their was a bunch of content in the description field that actually should have been separate fields (transaction codes, fees, all sorts of stuff). Basically instead of exporting a CSV format with fields for their structured data they took a date, description, amount, balance layout and then jammed all the extra data by appending strings to the description. I ended up using Perl to pre-process the data a bit and split some of the useful bits out into their own fields.

Today a [comment suggested](https://github.com/simonmichael/hledger/issues/868#issuecomment-508585335) regex CSV delimiters. I have never seen a file that didn't use single character delimiters, so this is a non issue for me, but it got me thinking...

What if the conditional matching command in the CSV import rules could use capture groups? Consider data looking like this?

```csv
"2019/07/04","Imaginary biz (16VO164I2) 2019/07/03 USD:5.578","100","165"
```

Being able to use capture groups would allow parsing more fields out of this data like so:

```ledger
fields date, description, amount, balance

if
,(.+) (\(.+\)) (\d\d\d\d/\d\d/\d\d) USD:([\.\d]+),
    description \1
    code \2
    date2 \3
    comment rate:\4
```

The import could end up like this:

```ledger
2019/07/04=2019/07/03 (16VO164I2) Imaginary biz  ; rate:5.578
    expense 100 = 165
    account
```

Given that regular expression are already supported in these matches, I'm hoping adding capture groups to them might not be too hard.

**Comment by simonmichael** [comment]
Labelled as a csv issue. Sounds good to me.. you too @adept ?

**Comment by alerque** [comment]
My current solution is to pre-process CSV imports with `perl` to munge the these sort of matches into columns `hledger` can parse. It would be nice combine these steps. Putting everything in a rules file instead of having one rule to pre-process and a second to import with make tweaks, maintenance, debugging, etc. a lot simpler.

**Comment by adept** [comment]
Lets talk about semantics here for a second. 

Firstly, semantics of a capture group that failed to capture anything. Let's say that capture group is really simple, like `(.*)`.

If it matched empty string, and we have `field = \1` in the body of the `if`, what would this mean? I see several potential implementations here, conflicting with each other:

1. We always assign value captured by capture group. For empty capture, empty string is assigned to `field` (i think this is what would currently happen if we write `field %5`, and `%5` turns out to be empty).

1. We always assign value to the field, but empty string is treated specially - `field` is unassigned (that is, there is no assignment to field after this `if`, even if previously we had one)

1. We only assign value of capture group if it is non-empty. For empty capture, nothing is done wrt `field` (it is left in its current state, whether it is assigned to something or unassigned)

Secondly, we need to talk about ifs with multiple regular expressions:
```
if
regex1
regex2
...
regexN
  body
```

1. What if different regular expressions capture different number of capture groups (including no groups)? How do we choose the match that will define assignment?

2. What if different regular expressions capture same number of capture groups, but these groups have different values? How do we choose the match that will define assignment?

Should we just disallow multi-regex ifs if we use capture groups? Or only allow them if at all times just one of the regular expressions will match?

**Comment by simonmichael** [comment]
Good questions. Also, conditional expressions will be getting more complex - assume they could be arbitrary boolean expressions of field-specific matchers.

**Comment by egli** [comment]
My use case is a subset of above functionality
```
if 
Budget Foods
Farmers Market
Bloor Street Market
  description \0
  account Expenses:Food
```

The point is that I could express in one rule that all these entries are `Expenses:Food` but the `description` should be the actual match.

A workaround that works now is to express above in multiple rules
```
if 
Budget Foods
  description "Budget Foods"
  account Expenses:Food
if 
Farmers Market
  description "Farmers Market"
  account Expenses:Food

etc.
```
 However given all the open questions above it is probably simpler to **not** implement this feature

**Comment by alerque** [comment]
To address some of the implementation details [raised above](https://github.com/simonmichael/hledger/issues/1061#issuecomment-567199277), I would suggest...

* Empty capture groups should produce empty values, and empty strings should be assigned (option 1). If people want to avoid empty assignments they can and should write regular expressions that don't match empty values (i.e. `(.+)` not `(.*)`).

* I would suggest not allowing mixing and matching regex rules with regular rules. Any time there would be ambiguity on what to do I would fail entirely with a parse error so as to avoid unexpected results. The primary failure case would be a differing number of capture groups. All expressions in an if statement should have the same number of captures. Zero (no regex) is incompatible with 1, etc. All `if` patterns would produce compatible results. Per the previous point it would be possible to add empty capture groups to force expressions to be compatible.

  One extra tweak could be very useful here. If capture group naming is allowed, only expressions with the same set of group names should be allowed. This would make it easier to group patterns by their possible outputs without having to have a different group for each possible ordering of fields.
