### ISSUE TITLE
CSV: amount field rewritten before applying rewrite rules

### ISSUE THREAD

**Issue by jblachly** [simonmichael/hledger#1089]
`hledger 1.15.2`

Documentation at https://hledger.org/csv.html indicates the following should work:

```
fields date,description,currency,amount
amount %amount %currency
```

A minimal test case shows that it does not, because the `amount` field is internally rewritten as %currency%amount **before** rewrite rules are applied:

test.csv.rules
```
skip: 1
fields: date,currency,amount,description,account1,account2
amount: %amount %currency
date-format: %Y/%m/%d
```

test.csv
```
date,currency,amount,description,account1,account2
2019/01/01,USD,$123.45,Test transaction,expenses:whatever,assets:whereever
```

hledger output:
```
2019/01/01 Test transaction
hledger: error: could not parse "USD$123.45 USD" as an amount
the CSV record is:       "2019/01/01","USD","$123.45","Test transaction","expenses:whatever","assets:whereever"
the amount rule is:      %amount %currency
the currency rule is:    %2
the default-currency is: unspecified
the parse error is:      1:12:
  |
1 | USD$123.45 USD
  |            ^
unexpected 'U'
expecting '@' or end of input

you may need to change your amount or currency rules, or change your skip rule
```

This works correctly if the field name is changed to `curr` (or whatever), suggesting that an `amount` field rewrite is performed internally prior to applying the rules.

**Comment by simonmichael** [comment]
Thanks for the report. I have no useful comment yet except I do remember something squirrelly like this, causing me to vary the field name:
```
fields   date,currency,amount_,description,account1,account2
amount  %amount_ %currency
```

**Comment by simonmichael** [comment]
Ah, here's an earlier issue: https://github.com/simonmichael/hledger/issues/500

**Comment by simonmichael** [comment]
Looking at this again, I think I can say that it's Functioning As Documented. There's already a currency symbol in the CSV amount field, and you're adding a second one by assigning to the special 'currency' pseudo-field in your fields list. The easy fix here would be to name that CSV field something else (or leave it unnamed if you're not using it).

**Comment by jblachly** [comment]
@simonmichael I respectfully disagree. Note that in the failing example, `USD` is added **twice**. This is in addition to the `$`.

I assert that the `amount field is internally rewritten as `%currency%amount` before rewrite rules are applied; this results in: `USD$nnn USD`, which is undocumented and incorrect.

**Comment by simonmichael** [comment]
Oops, I didn't notice the *three* currency symbols. Here's my latest attempt to understand/explain how it is interpreting these rules, using the latest master build and [latest CSV docs](https://hledger.org/csv.html#csv-rules) (because I know these best, and the result seems the same as 1.15):

```
fields: date,currency,amount,description,account1,account2
# 1. the second CSV field is named "currency" and assigned to the hledger currency field
#     for prepending to the hledger amount (when the final hledger amount is known)
# 2. the third CSV field is named "amount" and assigned to the hledger amount: $123.45

amount: %amount %currency
# 3. the hledger amount is reassigned, to a combination of the CSV amount field ($123.45)
#    and the CSV currency field (USD): $123.45 USD

# 4. the hledger currency field (USD) is prepended to the final hledger amount: USD$123.45 USD
```

Confusing, but I still think it's Functioning As Documented in latest docs. 
It might not be FAD in [1.15's docs](https://hledger.org/1.15/csv.html),
I don't have the will to dig through those right now...

**Comment by simonmichael** [comment]
Assuming the above is right, what can we say about this ? Eg, avoid these pitfalls:

- "currency" should not be used as a CSV field name if the CSV amount already contains a currency symbol [1]
- %currency should not be used in an amount field assignment [2]

1. because the CSV currency will be prepended to the amount, giving two currency symbols
2. because the CSV currency will be both prepended and interpolated

**Comment by gabor-udvari** [comment]
This is still an issue in the [1.19 docs](https://hledger.org/1.19/csv.html#setting-currency-commodity). Please note that the whole block reads like this:

> If the currency is provided as a separate CSV field, you can either:
>  * assign that to currency, which adds it to all posting amounts. The symbol will prepended to the amount quantity (on the left side). If you write a trailing space after the symbol, there will be a space between symbol and amount (an exception to the usual whitespace stripping).
>  * or assign it to currencyN which adds it to posting N's amount only.
>  * or for more control, construct the amount from symbol and quantity using field assignment, eg:
>    ```
>    fields date,description,currency,quantity
>    # add currency symbol on the right:
>    amount %quantity %currency
>    ```

Reading the first and last bullet-points after one another is the issue. The **more control** part suggests that the code snippet will get you this:
```
2019-11-12 Foo
    expenses:unknown           10.23 USD
    income:unknown            -10.23 USD
```

But in reality you will get this (not actually getting it because of the parsing error):
```
2019-11-12 Foo
    expenses:unknown           USD10.23 USD
    income:unknown            USD-10.23 USD
```

The provided code only gives you control over the amount field, and not the currency field. If the currency field is not empty, then it gets prepended to the left of the amount, regardless of the contents of the amount. That is totally fine, but the documentation should explain this. Also the documentation should provide a code snippet for achieving `10.23 USD`.

**Comment by simonmichael** [comment]
Thanks for the followup @gabor-udvari. I have rewritten https://hledger.org/csv.html#setting-currency-commodity (for master, at least..).

**Comment by gabor-udvari** [comment]
Thank you @simonmichael, it is clear now.
