### ISSUE TITLE
support GHC 8.8

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1090]
Related: 
- ~https://github.com/joelburget/easytest/issues/26 - we need a release of easytest supporting hedgehog 1.0.1; or we need to replace easytest~
- ~https://github.com/commercialhaskell/stackage/issues/4802 - we need a hledger release/revision supporting base-compat-batteries 0.11.0)~
- ~https://github.com/GaloisInc/json/issues/11 - we need a json release supporting ghc 8.8, for hledger-web~
  ~we need to replace json with aeson in hledger-web AddForm.hs~
- ~https://github.com/iconnect/regex/issues/173 - we need a regex release supporting ghc 8.8 for Shake.hs, before making our default stack.yaml use ghc 8.8~

**Comment by peti** [comment]
Stackage has switched to GHC 8.8.1 for the nightly builds and will release a new LTS version based on that compiler eventually. Is there any chance to get `hledger` ready for the new compiler in the foreseeable future so that it can be added to the LTS package set?

Personally, I don't see any problem supporting `base-compat-batteries`, but `easytest` has been causing trouble before and its authors don't appear to be particularly responsive either. :-(

**Comment by simonmichael** [comment]
Thanks for the ping. We are ready for base-compat-batteries (in master), but easytest now feels like a bit of a backwater (we are the only user) and I think it's unlikely to revive soon. I'd be happy to get hledger migrated to a mainstream testing lib, which I think at this point is tasty.

**Comment by peti** [comment]
Personally, I'd be hugely in favor of using `tasty` or `hspec` instead of `easytest`. At the moment, `hledger` is the only package left that I can't compile with ghc-8.8.1 -- mostly due to `easytest` --, and it feels like it has been like this once or twice before when new GHC versions have come out.

**Comment by peti** [comment]
Is anyone actively working towards this goal?

**Comment by simonmichael** [comment]
Negative

**Comment by simonmichael** [comment]
I ported unit tests to tasty, and have made hledger/ui/web build with ghc 8.8. hledger-web requires an unreleased version of json, which will keep it out of stackage until released (https://github.com/GaloisInc/json/issues/11). I'll leave this open for now.

**Comment by peti** [comment]
Yay, this is very good news! I just build the entire repo with ghc-8.8.x and it worked just fine.
