### ISSUE TITLE
Include journal with default commodity not applies

### ISSUE THREAD

**Issue by crispgm** [simonmichael/hledger#1170]
I define commodities and accounts in a `base.journal` like:
```
D ¥1,000.00
commodity ¥
    format ¥1,000.00

account expenses:accessories
...
```

And it is included in every journal:

e.g.
```
!include ../base.journal

2020/01/01 Bike
    expenses:transportation:bike     1.5
    liabilities:credit:bankcomm
```

The accounts work fine with accounts, but the commodities not applied.

**Comment by simonmichael** [comment]
Thanks for the report. This is a little bit tricky. Most directives, including `D`, apply only until the end of the file they are written in. So you would have to put that directive in the top-level file.

The manual section at https://hledger.org/journal.html#directives describes why it works this way. However I think there's a doc bug, since it says `D` can affect "all commodityless entries in all files". I guess it should say "following inline/included entries until end of current file or end directive".

**Comment by simonmichael** [comment]
I still had it wrong. Here's a summary of the new doc I'll commit, which I believe is accurate:
```
D

Effects:
declare a commodity to be used for commodityless amounts, and its number notation & display style

Scope of effects:
- default commodity: following commodityless entries until end of current file
- number notation: following entries in that commodity until end of current file
- display style: amounts of that commodity in reports
```

For comparison, here's `commodity`:
```
commodity

Effects:
declare a commodity and its number notation & display style

Scope of effects:
- number notation: following entries in that commodity in all files
- display style: amounts of that commodity in reports
```

As always, this is really confusing. I'm very tempted to break Ledger compatibility and simplify `D` so that it sets a default commodity only.

**Comment by crispgm** [comment]
Thanks for the explanation. So I have to put `D` in each journal file, that's unfortunate though I don't have too many files. Does anybody have workaround for this scenario?

**Comment by simonmichael** [comment]
Not each file; just the main one (top-most parent file).

**Comment by crispgm** [comment]
Okay,  I got that. Thanks very much.

**Comment by simonmichael** [comment]
I believe this is resolved for now.
