### ISSUE TITLE
Consider using "significand" in API, rather than "mantissa"

### ISSUE THREAD

**Issue by bradyt** [simonmichael/hledger#1178]
When attempting to use the hledger-web api, I noticed the word "mantissa". For example, see https://github.com/simonmichael/hledger/issues/985. Or from https://github.com/simonmichael/hledger/issues/316.

```json
          "aquantity": {
            "decimalPlaces": 2,
            "decimalMantissa": 100
          },
```

I think this is unnecessarily ambiguous. I think "significand" would be a better word.

Note that a search reveals two related results at https://en.wikipedia.org/wiki/Mantissa. One is https://en.wikipedia.org/wiki/Common_logarithm#Mantissa_and_characteristic, which suggests "The fractional part is known as the mantissa." The other is https://en.wikipedia.org/wiki/Significand, which suggests to prefer the term "significand" for this.

To give a concrete and simple example, take 123.45. Then 12345 is the significand, whereas the mantissa would be 0.09151220162777171.

If your API uses the word mantissa, noone will know what it means until they test values. But if you use the word "significand", everyone will know what you mean.

**Comment by PaulJohnson** [comment]
I'm the author of the [Decimal package](https://hackage.haskell.org/package/Decimal-0.5.1) which is being used here. [The  hledger code](https://github.com/simonmichael/hledger/blob/hledger-web-1.16/hledger-web/Hledger/Web/Json.hs#L130) uses Generic to derive a JSON instance for `DecimalRaw`, so the JSON field names are taken from the Haskell definition.

Obviously changing the JSON would be a breaking change for any clients, so that is reason enough not to do it. It also obfuscates the relationship with the underlying Decimal type.

I'm not going to change the field name in `Data.Decimal`.

When I ask Google for the dictionary definition of "mantissa" the second definition is "[Computing]
the part of a floating-point number which represents the significant digits of that number." So while I do see that the term now appears to be deprecated, its not as obscure as all that.

It is also the word that was used back when I was at University. Checking a couple of books, "Numerical Recipes in C" uses "mantissa", while Knuth uses "fraction", and makes the point about "mantissa" being related to logarithms.

**Comment by simonmichael** [comment]
Thanks @bradyt and @PaulJohnson. I think it's pretty clear from context what's meant here, and the usage is widespread enough. I don't think we need to do anything special on the hledger side either.

**Comment by simonmichael** [comment]
This could be mentioned this in the appropriate place when we have more detailed [JSON API docs](https://hledger.org/hledger-web.html#json-api). For now, closing.
