### ISSUE TITLE
Duplicates bug in hledger accounts sub-command

### ISSUE THREAD

**Issue by psb777** [simonmichael/hledger#1182]
The hledger accounts sub-command shows the same account twice if (1) it is declared with a comment using the 'account' directive and (2) the account is used in a transaction. Smallest example I could construct is this:

```
$ cat a.ledger
account assets:bank ; NatWest 12-34-56 12345678

2020/01/01
    assets:bank      -10
    expenses

$ hledger accounts -f a.ledger 
assets:bank ; NatWest 12-34-56 12345678
assets:bank
expenses
```
The second line of the output should not appear.

```
$ hledger --version
hledger 1.14.2
```

Platform: Linux Devuan Ceres (Debian sid without systemd)

**Comment by simonmichael** [comment]
Thanks for the report. Because account names can contain single spaces, the comment needs two spaces before it, otherwise it is considered part of the account name. https://hledger.org/journal.html#account-comments doesn't mention this.

How should this work ? We want to be consistent with the rest of hledger and not create hard-to-remember special cases. There are some places where we require the double space as separator, eg: 

- between account name and amount in a posting
- between period expression and transaction description in a periodic rule

This a probably necessary evil, and we try not to do this too much.

Here we have the semicolon delimiter, so we needn't require two spaces.. but only if we are ok with disallowing semicolon in account names. This would be a change in functionality; semicolon has always been allowed in account names. Changing this would require a mail list discussion and a consensus that it's ok. And it would reduce compatibility with Ledger.

The easy, though not beautiful, fix is to document that two or more spaces are required between account name and comment, just the same as in postings.

**Comment by simonmichael** [comment]
https://hledger.org/journal.html#account-comments update.
