### ISSUE TITLE
balancesheet giving wrong percentages in master

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1309]
It looks like something has gone awry since 1.18: hledger bs -% shows no totals and the percentages don't add to 100.

**Comment by Xitian9** [comment]
I think the lack of totals is due to #1260, which was introduced to address #1234. A compound balance report has always turned --no-totals on when you use percentages. I don't know why.
https://github.com/simonmichael/hledger/blob/22091dfd31f83b0d41a5c5f4bd01a9891e407995/hledger/Hledger/Cli/CompoundBalanceCommand.hs#L103-L107

As for the totals not summing to 100%, could you give an example where that happens? It often didn't add up to 100% before (for example, run `hledger bs -% -f examples/sample.journal`). I'm actually not clear an what the percentage is supposed to mean when you have a mix of positive and negative values, inclusive and exclusive values, etc.

**Comment by simonmichael** [comment]
Thanks for the fix! Re not adding to 100, I should have given an example; can't reproduce any glaring problem now. 
Except that `hledger bal -% -f examples/sample.journal` gives me all zeroes. I'm confused by this too. https://github.com/simonmichael/hledger/commit/79ca4a76 was the commit introducing bs -%, and I think it says something about bal too. Certainly -% has not been tested in every nook and cranny, and if anyone wants to do that, it's welcome, but now we're on par with or better than 1.18 which is good.

**Comment by simonmichael** [comment]
PS a separate issue, but here's an example of bal showing zeroes. It does this whenever the grand total is zero, and the commit message mentions it. 
```
$ stack exec -- hledger -f examples/sample.journal bal -%
                   0  assets:bank:saving
                   0  assets:cash
                   0  expenses:food
                   0  expenses:supplies
                   0  income:gifts
                   0  income:salary
                   0  liabilities:debts
--------------------
                   0
```

bs doesn't do it, and I suspect bal should be more like it:
```
$ stack exec -- hledger -f examples/sample.journal bs -%
Balance Sheet 2008-12-31

                    || 2008-12-31 
====================++============
 Assets             ||            
--------------------++------------
 assets:bank:saving ||    100.0 % 
 assets:cash        ||   -200.0 % 
--------------------++------------
                    ||   -100.0 % 
====================++============
 Liabilities        ||            
--------------------++------------
 liabilities:debts  ||   -100.0 % 
--------------------++------------
                    ||   -100.0 % 
====================++============
 Net:               ||          0 
```

**Comment by simonmichael** [comment]
Though, I admit haven't worked out what exactly bal should show, and maybe the fact that bs has subtotals make a difference ? Anyway I leave it here as a data point.
