### ISSUE TITLE
hledger-web period argument/option causing sidebar to show no accounts

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1320]
With this journal,
```
2012/12/31
  (assets:checking)  1

2013/1/1
  (assets:checking)  1

2013/2/1
  (assets:checking)  1
```
`hledger-web date:2013/1` or `hledger-web -p 2013/1` filters the register properly, but also shows no account balances in the sidebar, which is unexpected. I don't remember what effect queries are supposed to have on the sidebar accounts - perhaps none, but definitely not this.

**Comment by Xitian9** [comment]
I'm either not able to reproduce this or don't understand what the problem is. When I run the given command in master, I get a single transaction displayed (2013/1/1, 1 into assets:checking, as expected), and the left sidebar shows an inclusive value of 1 in each of assets and assets:checking (displayed indented in tree mode, no boring parent ellision at this stage.)

**Comment by Xitian9** [comment]
Just coming back to this: I'm still not able to reproduce. I think this might not be an issue anymore.

**Comment by simonmichael** [comment]
Yup, this was fixed.
