### ISSUE TITLE
a bit more review of the 4 digit year requirement

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1339]
These commits changed date parsing to require at least four digits in years:

dc41cee2 lib: datep now requires years to be at least four digits. Stephen Morgan* 7/30/20, 6:17 PM
ffb5cf07 lib: Ensure parsed years have at least 4 digits. Stephen Morgan* 7/28/20, 6:00 AM

@Xitian9 I remember our discussion, but not quite what motivated this or what problems it solves. I had second thoughts about it while preparing 1.19, because it can break existing journals that were previously valid, and because the parse error needs a bit more work:

      |
    1 | 200/10/16
      | ^^^^^^
    well-formed but invalid date: 2020/200/10

I had trouble reverting it just now so I'm moving forward but noting it here for followup.

**Comment by Xitian9** [comment]
The four-digit year requirement was there in some places to distinguish `M/D` format from `Y/M` and `Y` from `D`. I had originally removed the four-digit requirement, instead parsing it as a year if it were larger than 12 or 31, respectively.

It was decided that instead of removing the four-digit requirement, things should by made consistent by requiring four-digit years everywhere, including in places where it wasn't previously required.

What is happening in that error message, is it's parsing it as `M/D` format, and filling in the year from the current date. It apparently stops parsing when it sees the final `/`, so it's ignoring the final `/16`. I agree the error message can be improved. Perhaps the date parser should make sure there's not another date separator at the end.

**Comment by simonmichael** [comment]
I didn't easily see a good way to improve the parse error. No complaints from users so far, closing.
