### ISSUE TITLE
Unexpected market price valuation

### ISSUE THREAD

**Issue by erikryb** [simonmichael/hledger#1402]
Hi, I encountered the following strange behaviour. With the following journal:

```
2020-11-10 Transaction
    account1  B 1.00
    account2

P 2020-11-01 B C 2
P 2020-11-02 C A 3
P 2020-11-03 B A 5
```

i get

```
> hledger bal -X A account1
                 A 6  account1
--------------------
                 A 6
```

while I expected this:

```
> hledger bal -X A account1
                 A 5  account1
--------------------
                 A 5
```

If I remove the two first price declarations, I get the expected result:

Journal:
```
2020-11-10 Transaction
    account1  B 1.00
    account2

P 2020-11-03 B A 5
```

Result:
```
> hledger bal -X A account1
                 A 5  account1
--------------------
                 A 5
```

Also, if I change the latest price to a decimal number, I also get the expected result:

Journal:
```
2020-11-10 Transaction
    account1  B 1.00
    account2

P 2020-11-01 B C 2
P 2020-11-02 C A 3
P 2020-11-03 B A 0.5
```
Result:
```
> hledger bal -X A account1
               A 0.5  account1
--------------------
               A 0.5

```

It appears that the evaluation strategy sometimes choses to evaluate using the chain B -> C -> A, even when there is a direct conversion rate from B -> A available with a newer date.

**Comment by simonmichael** [comment]
Good catch, thanks for the report!

--debug may give more insight.

**Comment by erikryb** [comment]
I simplified it further, the bug appears also without chained conversion rates. The ledger:

```
2020-11-10 Transaction
    account1  B 1.00
    account2

P 2020-11-01 B A 5.00
P 2020-11-02 A B 0.40
```

gives

```
valuation date: 2020-11-21
market price for B -> A: 2.50000000
              A 2.50  account1
--------------------
              A 2.50
```

which is correct. However, the ledger

```
2020-11-10 Transaction
    account1  B 1.00
    account2

P 2020-11-01 B A 5.00
P 2020-11-02 A B 0.10
```

gives

```
> hledger bal -X A account1 --debug
valuation date: 2020-11-21
market price for B -> A: 5.00000000
              A 5.00  account1
--------------------
              A 5.00
```

which is incorrect, since it uses the first price directive, instead of the latest.

**Comment by simonmichael** [comment]
@erikryb thanks for the second example. I have fully paged back in the details of the valuation code, but I seem to be seeing at least two bugs here. I'm a little surprised we haven't noticed sooner.

1. Causing your second example: I never deduplicated the forward prices and reverse prices correctly, so it was too eager to use reverse prices. This one is now fixed in master.

2. Causing your first example: it should be picking the direct B->A price as the shortest path from B to A, and instead it seems to be wrongly picking a longer indirect path. Here's the (latest) debug output:
```
ghci> :main -f a.j bal -N -X A
makePriceGraph 2020-11-22:
 PriceGraph
   { prGraph = mkGraph
     [ ( 0, "A" ), ( 1, "B" ), ( 2, "C" ) ]
     [
       ( 0, 1, 0.2 )
     ,
       ( 0
       , 2
       , 0.333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333
       )
     ,
       ( 1, 0, 5 )
     ,
       ( 1, 2, 2 )
     ,
       ( 2, 0, 3 )
     ,
       ( 2, 1, 0.5 )
     ]
   , prNodemap = NodeMap
     { map = fromList [ ( "A", 0 ), ( "B", 1 ), ( "C", 2 ) ], key = 3 }
   , prDefaultValuationCommodities = fromList
     [ ( "B", "A" ), ( "C", "A" ) ]
   }
shortest price path:
 Just
   [ 1, 2, 0 ]
                 A 6  a
```
fgl:Data.Graph.Inductive.Query.SP.sp should have picked the [0,1] path here, not the [1,2,0] path. sp has mostly been working for us until now as far as I'm aware. The only issue I found for it is https://github.com/haskell/fgl/issues/67 , perhaps it's relevant ?

**Comment by simonmichael** [comment]
Fixed in master I believe.
