### ISSUE TITLE
Market prices aren't inferred from its recent transaction

### ISSUE THREAD

**Issue by zhzy0077** [simonmichael/hledger#1853]
Given below journal file:
```
2022-01-01 * Buy BTC
    assets:Cash              -100 USD
    assets:BTC     100 BTC @@ 100 USD

2022-01-15 * Buy BTC
    assets:Cash              -100 USD
    assets:BTC     200 BTC @@ 100 USD
```

When I run query `hledger areg assets:BTC -X USD --infer-market-prices`, hledger shows:
```
Transactions in assets:BTC and subaccounts:
2022-01-01 Buy BTC               as:Cash                   50 USD        50 USD
2022-01-15 Buy BTC               as:Cash                  100 USD       150 USD
```
When I run query `hledger bs -M -X USD --infer-market-prices`, hledger shows:
```
Balance Sheet 2022-01-31, valued at period ends

             || 2022-01-31 
=============++============
 Assets      ||            
-------------++------------
 assets:BTC  ||    150 USD 
 assets:Cash ||   -200 USD 
-------------++------------
             ||    -50 USD 
=============++============
 Liabilities ||            
-------------++------------
-------------++------------
             ||            
=============++============
 Net:        ||    -50 USD
```
So I'm assuming hledger picks the earliest market prices inferred among the period - in this case, 1 BTC => 1 USD.

Would it make more sense that hledger evaluate each transaction's market price by its own date?

**Comment by Xitian9** [comment]
What hledger is actually doing here is using the later price, and evaluating it at the end date of the period. The calculation is
At 2022-01-31, the value in assets:BTC is 300 BTC. The most recent price we have (using --infer-market-prices) is 200 BTC = 100 USD, so 0.50 USD per BTC. So multiplying 300 BTC you get 150 USD.

Are you looking to convert to cost, rather than valuation? Try using `--cost` instead of `-X USD`? Alternately, you might be looking to do full valuation, but at the date of each transaction, in which case you are looking for `--value=then,USD`. If you could let us know what output you're expecting, we can help you further.

**Comment by Xitian9** [comment]
You might find this link useful: https://hledger.org/hledger.html#effect-of-valuation-on-reports.

**Comment by zhzy0077** [comment]
Thank you. `--value=then,USD` is really what I'm looking for. Also the documentation you provided helps a lot.
Appriciate.
