### ISSUE TITLE
Date format codes

### ISSUE THREAD

**Issue by glennra** [simonmichael/hledger#1888]
Where are the date formats for CSV import specified?
The only clues I can find are here: https://hledger.org/import-csv.html
```
# specify the date field's format - not needed here since date is Y/M/D
# date-format %-d/%-m/%Y
# date-format %-m/%-d/%Y
# date-format %Y-%h-%d
```
I assume that that the '%-n' format code means add a leading zero.

The reason I'm asking is that I have a CSV file that I'd like to import and the dates use an abbreviated year, e.g 21/12/31 instead of 2021/12/31, and I'm trying to figure out if I can tell hledger to fix it during import.

So what I'd like to know is: is there a format code for an abbreviated year and a way to specify the century?

**Comment by simonmichael** [comment]
https://hledger.org/1.26/hledger.html#date-format is the best place (see link).

**Comment by the-solipsist** [comment]
I think this issue can be closed, since the information is readily available and should be easy to find.  (import-csv.html says: "This is described in detail in the [hledger manual](https://hledger.org/hledger.html#csv-format), but here are some quick examples.")

Please re-open if there's any additional work left.
