### ISSUE TITLE
GitHub Release for 1.26.1 is missing binaries

### ISSUE THREAD

**Issue by tech189** [simonmichael/hledger#1900]
https://github.com/simonmichael/hledger/releases/tag/1.26.1 says there should be binaries a few days after release, however it was released 20 days ago. As a result the Chocolatey and Scoop packages for Windows are out of date. Could you please check these, thanks!

**Comment by simonmichael** [comment]
Thanks for the report. Because of a problem with the binary build action, and because these binaries are essentially the same as the 1.26 binaries, I didn't bother. I should at least add a note explaining this.

But, I suppose this affects packaging systems as you say, at least making them look out of date. So I guess I'd better try to get those binaries in place.

**Comment by simonmichael** [comment]
I have uploaded 1.26.1 binaries. 

Related: https://gitlab.haskell.org/ghc/ghc/-/issues/20266

**Comment by tech189** [comment]
Thank you very much!
