### ISSUE TITLE
Inconsistency between documentation and code: * comments missing from csv rules

### ISSUE THREAD

**Issue by sprig** [simonmichael/hledger#1953]
Hello and thanks for creating and maintaining hledger!

I just spent some time trying to figure out what lines starting with `*` mean, in a rules file (that I wrote a while ago, moreover). Suspected and eventually confirmed to be comments by the below referenced line, nowhere in the docs is `*` mentioned as an allowable comment character, as far as I can tell, including in specification laid out in the same file. I did eventually find https://hledger.org/1.28/hledger.html#comments which allows for `*` comments in the journal, which I presume is why I tried the same in the rules file.

Definition:
https://github.com/simonmichael/hledger/blob/68a912286b00a72cfed788c25c7619b158bbadd4/hledger-lib/Hledger/Read/CsvReader.hs#L444
Spec: https://github.com/simonmichael/hledger/blob/68a912286b00a72cfed788c25c7619b158bbadd4/hledger-lib/Hledger/Read/CsvReader.hs#L403
Documentation:
First paragraph of https://hledger.org/1.28/hledger.html#csv-rules

**Comment by simonmichael** [comment]
Thanks! I have clarified the support for `*` comment lines in [CSV rules](https://hledger.org/dev/hledger.html#csv-rules), [timeclock](https://hledger.org/dev/hledger.html#timeclock-format) and [timedot](https://hledger.org/dev/hledger.html#timedot-format) formats.

**Comment by simonmichael** [comment]
Though FWIW, supporting `*` comment lines seems no longer valuable. Nowadays, Emacs users like myself probably prefer using ledger-mode plus outshine-mode to fold journals, rather than switching to org mode and losing the benefits of ledger-mode. I still find it useful for timedot files, but that could change. If anyone wants to champion it, we could explore deprecating and eventually dropping this syntax.
