### ISSUE TITLE
Incorrect sample script resolver

### ISSUE THREAD

**Issue by VOID404** [simonmichael/hledger#2036]
The `lts-20.13` has old `hledger`
https://github.com/simonmichael/hledger/blob/4a61caefd760e0eb74c53f1daa421326e43fd7f3/bin/hledger-script-example.hs#L4-L5

Resolver | `hledger`
--|--
[LTS Haskell 20.13](https://www.stackage.org/lts-20.13) | [1.27.1](https://www.stackage.org/lts-20.13/package/hledger)
[LTS Haskell 20.21](https://www.stackage.org/lts-20.21) | [1.27.1](https://www.stackage.org/lts-20.21/package/hledger)
[Stackage Nightly 2023-05-20](https://www.stackage.org/nightly-2023-05-20) | [1.29.2](https://www.stackage.org/nightly-2023-05-20/package/hledger)
Latest on Hackage | [1.29.2](https://hackage.haskell.org/package/hledger)

The script uses `Hledger.Cli.Script`, which was added in `1.29`.
https://github.com/simonmichael/hledger/blob/4a61caefd760e0eb74c53f1daa421326e43fd7f3/bin/hledger-script-example.hs#L13

To make the example work we'd have to use the `nightly` resolver.

**Comment by VOID404** [comment]
<img width="1663" alt="Screenshot 2023-05-21 at 09 28 11" src="https://github.com/simonmichael/hledger/assets/9433601/34cab62d-2ccd-4610-8925-910096f81466">

**Comment by simonmichael** [comment]
Thanks for this report. Running it that way doesn't work out of the box, unfortunately. Instead you have to be inside the hledger source tree, so that `stack runghc` uses that version of hledger, which is guaranteed to be compatible.

Currently the bin scripts generally, and this one in particular, are set up to use the corresponding hledger source, which is guaranteed to be compatible. (See eg the comments at the top of hledger-script-example.hs.) Ie they are currently optimised for development and tweaking, not for "use from anywhere". It's not ideal; sorry about that. Of course you can locally fix the scripts to use a released hledger version, as you have done.

**Comment by simonmichael** [comment]
I think the procedure at https://hledger.org/scripts.html#install-scripts (`cd hledger; bin/compile.sh`) is one way around this.
