### ISSUE TITLE
web: Would be convenient if the insert-order of the text-file was reflected in the list order on the website

### ISSUE THREAD

**Issue by silky** [simonmichael/hledger#2060]
Using hledger 1.27.1 I find that the website (surprisingly) lists the items in reverse order that they appear in the text file, for entries on the same day.

Consider:

```
2023-07-15
    a  1
    b

2023-07-15
    a  2
    b

2023-07-15
    a  3
    b
```

Gives:

![image](https://github.com/simonmichael/hledger/assets/129525/de5b6933-6519-4cb2-8cce-1ade5c65778e)

I'm not sure if this is intentional? It was a least slightly unexpected. Clearly it's not massively important, but it'd be nice if they could agree :)

**Comment by simonmichael** [comment]
hledger-web lists transactions newest-first, because I found it a lot more usable when you have a lot of transactions. 

At https://demo.hledger.org there's a caret indicating this (I guess you are using an older version). It's currently not clickable to reverse the order alas.

**Comment by simonmichael** [comment]
(hledger CLI reports do show things in forward date order.)

**Comment by silky** [comment]
Just to be clear, I don't mind that it's newest-first, I'm just noting that _when the dates are the same_ I would've expected it to default to the order in the text file (i.e. the one at the top of the text file is first).

But maybe this is unexpected, and people prefer to _append_ to the text file, instead of what I was doing, maintaining the _newest at the top_ of the text file as well ... ?

**Comment by simonmichael** [comment]
Interesting! Yes I and all data entry tools add new entries at the bottom of the journal file, because it's easier and safer (appending does not alter existing data).  It's not required but I think most people do this.

Regardless of order within the file, `hledger print` prints transactions in 1. date order 2. parse order. Ie entries on the same date will be displayed in the other they appear in the file(s), from top to bottom. `hledger-web` lists transactions in the reverse of this order.

**Comment by silky** [comment]
Ah I see, okay, fair enough then; that makes sense.

Thanks!
