### ISSUE TITLE
print needs more control over amount precisions

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#2085]
Since 1.31, `print` preserves original amount precisions, without standardising them. This is the right default behaviour, but I meant to allow overriding it with `-c`, and ran out of time. That is needed because otherwise there's no way to generate journal entries with consistent precisions, eg from a CSV with inconsistent decimal places.

Here's a proposal for supporting several kinds of precision cleanup with `print`:
[see #2101]

(Not a regression, since the change was documented.)

**Comment by wgslr** [comment]
I'm glad to see this ticket! I use `hledger print` for autoformatting my journal after adding entries by hand. Having the trailing zeros added was the desired behavior in this case and I was disappointed to see it change in 1.31 (but I guess it was a necessary change, as I have also seen issues with transactions becoming unbalanced due to rounding). 

Aparat from the `-c` flag, could we also have a command line flag saying "enforce rounding according to the _commodity_ directives"? I'd like to avoid writing out CLI arguments for each of the commodities I have already defined.

**Comment by simonmichael** [comment]
Yes, both of these should be fixed soon.

**Comment by simonmichael** [comment]
@wgslr #2101 is ready FYI.

**Comment by wgslr** [comment]
Awesome, thanks for the notification!

**Comment by simonmichael** [comment]
Resolved in master; the old behaviour is available with `print --round=soft`.
