### ISSUE TITLE
Strange assertion error

### ISSUE THREAD

**Issue by ipvych** [simonmichael/hledger#2150]
Originally reported in mailing list: https://groups.google.com/g/hledger/c/UXBTSuTB-6s

My `hledger --version` is `hledger 1.30.1, linux-x86_64`

I noticed this at the end of the year when closing my balances that there was one posting that was being reported as not balanced by assertions even though it is balanced according what `hledger reg -I` and `hledger bal -I` reports and after a few tries managed to reproduce it down to following journal file:

```ledger
2023-02-12 Withdraw
    assets:cash:mono:saved:rent  400 UAH
    equity:test

2023-06-17 Exchange
    assets:cash:petty:saved:rent  4.00 EUR @@ 400 UAH
    assets:cash:mono:saved:rent  = 0 UAH

2023-12-31 closing balances
    assets:cash:petty:saved:rent  -4.00 EUR = 0.00 EUR
    equity:opening/closing balances
```
When running hledger with this it reports balances as unbalanced. Removing the currency from assertion in "closing balances" transaction or removing assertion entirely from "Exchange" transaction removes the error.

**Comment by simonmichael** [comment]
Ccing:

> Hello.. hmm. I see it works in 1.29. I would guess it's caused by this change in 1.30:
> 
> - Balancing a transaction with a balance assignment now properly respects costs.
> 
> Related:
> https://github.com/simonmichael/hledger/issues/2039
> https://github.com/simonmichael/hledger/issues/2038
> https://github.com/simonmichael/hledger/commit/d19d8664461e880a2497966567899e7964cad2c3
> https://hledger.org/dev/hledger.html#balance-assignments-and-costs

**Comment by simonmichael** [comment]
Well. This is a small example, but there's quite a lot going on, it touched a lot of tricky code and for various reasons took me a loong time to solve. It was indeed a regression in 1.30..1.32, a latent bug checking mixed-cost balances, exposed by the fix for #2039. It turns out @usaAmch reported this first as #2137. Please feel free to claim your $50 https://hledger.org/REGRESSIONS.html#regression-bounty when convenient.

Among other things, this showed me some misleading haddocks, some misleading amount display helpers, and some looseness in our amount types:

- Amounts with and without a cost attached are represented by the same type
- MixedAmounts can be normalised (one Amount per commodity and cost) or unnormalised (multiple Amounts with the same commodity and cost)
- MixedAmounts even when normalised, can be costless, can have some Amounts with costs, can have all Amounts with costs, can have multiple Amounts in the same commodity but with different costs

**Comment by simonmichael** [comment]
Hi @ipvych, I invite you to claim your $50 regression finder's bounty, offered on this issue on 2024-01-24. You can claim it within the next week, at https://hledger.org/REGRESSIONS.html#regression-bounty ; after that time it will convert to a project donation.

**Comment by ipvych** [comment]
Hello, thank you for the reminder, I have submitted the invoice.
