### ISSUE TITLE
CSV Import through hledger-web

### ISSUE THREAD

**Issue by stephenmac7** [simonmichael/hledger#220]
It would be nice to be able to upload a rule file and csv through the web interface, especially for those who are not well versed in the usage of shell redirection. Once uploaded, the contents (possibly once reviewed) would be appended to the current journal file.

**Comment by ndarilek** [comment]
What are the chances of this being implemented?

I'm working on bringing HLedger to [Sandstorm](https://sandstorm.io), a platform for easily and securely deploying server-based apps as easily as you install apps on your smartphone.

Unfortunately, Sandstorm sandboxes are not shell-accessible, meaning you can't just dump data into a directory and then manage it by hledger-web. So some type of CSV import via the web would be essential.

Not sure if this already exists, but journal upload/download would be useful too. Perhaps something that concatenates an uploaded journal onto an existing one.

It'd be great to see this feature land. With a Sandstorm package plus a few additional, minor tweaks, hledger-web could essentially become a secure, multi-user app with the ability to delegate read/write access to the journal. All you'd need is the ability to check a few HTTP headers and toggle display of interface components based on their contents. But web-based import and export is the big missing piece to make this usable on Sandstorm.

Thanks.

**Comment by simonmichael** [comment]
Exciting!

The code to accept full journal edits through the web is there, just disabled in recent releases. CSV import/export through the web is not yet there and needs UI design and implementing.

If you can demo the existing hledger-web as a Sandstorm app and some of the benefits (access control you say ?), I think it will stir up a lot of interest in adding more support.

**Comment by ndarilek** [comment]
Unfortunately, I can't quite wrap my head around Haskell well enough to
do much with it. However, the first version of the Sandstorm integration
should at least have the ability to do a one-click install and share
full journal access securely with no code modifications (I.e. you could
create a journal, send someone a link to have full access, then later
delete that link and revoke it.) Finer-grained access is just a matter
of parsing an HTTP header that Sandstorm passes and enabling/disabling
bits of the UI based on its contents (I.e. maybe if the "writer"
permission isn't present then the transaction add form is disabled, and
the code to add them won't accept user input.)

So, great to hear that you're receptive, because I'll likely need help
on the back-end. :) I'll open a new issue with more specifics, but in
the meantime it's good to hear that there's interest, and that at least
some of this code already exists.

**Comment by simonmichael** [comment]
Needs discussion/developers, reopen when active.
