### ISSUE TITLE
balancesheet --row-total with HTML output lacks data in the Total column

### ISSUE THREAD

**Issue by thielema** [simonmichael/hledger#2251]
While working on `compoundBalanceReportAsHtml` I noticed that
~~~~
$ hledger balancesheet --yearly --row-total --output-file=balancesheet.html
~~~~
shows a `Total` header but misses data in the `Total` column. In Text output the `Total` header is absent, so header and data is consistent.
Missing data also means, that `--row-total --average` together put average values into the total column.
The problem exists at least since hledger-1.28.

This is certainly related to: https://github.com/simonmichael/hledger/issues/2225

Is there a reason to omit the `Total` column in `balancesheet`? In `incomestatement` it is present.
I think the simplest thing would be to support total columns in all flavors of `CompoundBalance`.

**Comment by simonmichael** [comment]
Thanks for the report. Yes, it was intended that -T/--row-total be ignored by balancesheet and balancesheetqeuity, since they show end balances and summing those is not meaningful. This was changed in hledger 1.23 apparently, though not mentioned in release notes. But the headings in html output were overlooked until now.

**Comment by thielema** [comment]
I see there is the `totalscolumn` variable, that is `False` for Historical and Cumulative reports. I think I can fix the problem.

I am still uncertain, why are `balancesheet` and `incomestatement` different in this respect.

**Comment by simonmichael** [comment]
Think of a report like `hledger is -M` (`hledger incomestatement --monthly`). Each column shows revenues/expenses in the period, and it makes sense to add those up and see a total across all periods. The same is not true for `bs`/`bse`, where each column shows an end balance at the end of each period, showing a total of those does not make sense. And of the many sources of confusion for new accountants, this is one we can prevent, by not showing it.

**Comment by thielema** [comment]
On Wed, 9 Oct 2024, Simon Michael wrote:

> The same is not true for bs/bse, where each column shows an end balance 
> at the end of each period - showing a total of those does not make 
> sense. And of the many sources of confusion for new accountants, this is 
> one we can prevent, by not showing it.

I see. I would prefer if invalid option combinations would be rejected by 
the option parser. But the current policy seems to be to ignore 
conflicting flags. With optparse-applicative we could express such logic 
connections. However, this would be a major rewrite and it would also 
affect RecordOpts et.al. since it should comply with the flag logic.

**Comment by simonmichael** [comment]
> I see. I would prefer if invalid option combinations would be rejected by the option parser. 

I hear you, and normally I prefer to give a clear error rather than possibly mislead the user.
But I feel there is a trade off here.

But we have many options and many commands, and it's somewhat inevitable
that some combinations of these won't make sense or won't be implemented yet.
So current policy is largely to ignore those cases, because strictly raising an
error for each is (a) more work to do consistently and (b) I feel would make the CLI
feel "spiky" and less comfortable to use.

For example: I often explore reports by substituting one command for
another while keeping options the same, or vice versa. Or I have some
command saved as an alias or script, and I override it with additional
command line option. Sometimes these variants have superfluous options
as a result, but they don't get in the way. If we would strictly
reject those, this kind of exploratory command line use would be
harder.

**Comment by simonmichael** [comment]
https://hledger.org/dev/hledger.html#options is where this policy could be made clearer if needed. Current text "the following general options are common to most hledger commands" is trying to suggest it. Likewise "Many of these work with the higher-level commands as well." at https://hledger.org/dev/hledger.html#balance-features .
