### ISSUE TITLE
A "tags" reporting command.

### ISSUE THREAD

**Issue by maisammusthafa** [simonmichael/hledger#261]
Here are some features I would like to see in hledger.
1. A "tags" reporting command that will report a list of all the tags in the journal (even the tags with values, and multiple tags on single lines). The list will show only unique tags, and will be sorted alphabetically.
2. A --values flag for the "tags" reporting command that will report the tags and their values (only tags with values will be shown).
3. A --count flag for the "tags" reporting command that will show how many times each tag has been used.

This will help greatly when using tags in queries since the user will know exactly what tags to query.
##

**Comment by imransobir** [comment]
+1, would like to see this feature as well.

**Comment by simonmichael** [comment]
Great idea. I have not used tags heavily enough to need it, but I can see how it would be useful. The accounts command, and maybe the stats command, should give some ideas if someone would like to work on it.

**Comment by the-solipsist** [comment]
I feel it would be useful to print tag values as well when printing the tags.

**Comment by simonmichael** [comment]
I had forgotten this issue, but the tags command arrived recently, in hledger 1.4. We can improve it further: 

Currently any arguments filter the transactions in which tags are discovered. Today I found this unintuitive (see #hledger log) and I propose to add a new first argument which filters the tag names themselves, ie changing the UI to `hledger tag [TAGNAMEREGEX [QUERYARGS]]`.

Note you can see tag values now by using the accounts command and --pivot: `hledger --pivot TAGNAME accounts`. Is `tags --values` still needed ? If so what should the output look like ?

How should --count's output look ? Should --count interact with --values ? 

A related report which gives some idea of tag activity: `hledger activity tag:TAGNAME`

**Comment by simonmichael** [comment]
There is some overlap between these tag reporting desires and our usual reports. We could add some features generalising these:

- a different kind of pivot. Instead of using the values of a single tag as account names, it would use tag names and values combined as account names. Might or might not be useful to expose in UI.
- a --count mode. Instead of reporting summed amounts, it would report the number of postings. Could be used with any reports.

Given the above, we could produce pseudo balance reports including tag names, tag values, and accumulated counts of both, displayable in any of the ways we display balance reports.

**Comment by ony** [comment]
I clearly can see benefit of listing all unique names of tags and all tags with their corresponding values to identify misspelling or to provide input for auto-completio (especially with filtering).

But I'm not sure I understand use-case for `--count`. Is it to place most frequent tags in a top list of auto-completion? Or identifying which tags are used infrequently and might be a subject for stripping from journal?

**Comment by simonmichael** [comment]
@maisammusthafa, why do you want to see counts ? I might use it for things like:

- I found similar/redundant tags, which one is the most used ? (Currently in this situation I compare activity reports, which is more verbose)

- How many open TODO: tags do I have, by year ?

- How many trips did I have by year ? (distinct values of trip: tag)

- Seeing average counts per period (if full proposal implemented)

**Comment by ony** [comment]
Do we still need this issue open?  
In 0b793bca1bb2fa570f0c66a80085b300353050e0 (included in v1.15) `tag` command got `--values` flag.

I'm not sure how `--count` will help user to understand which tags to query other than comparing how good tags at selecting smaller set of transactions. Though in case if tags have hierarchical relations and in advance only perceived as "my target transaction should have both of them", it is natural to query on both of them rather than choosing one among them.

Note as well that `hledger stat tag:ABC` will give amount of transaction for particular tag (or value in case of query `tag:ABC=DEF`).

I think if we consider `--count` for `tags`, it worth to consider that for `accounts` as well.

**Comment by simonmichael** [comment]
Closing this for now. https://hledger.org/hledger.html#tags is (brief) documentation of the current tags command. There are a lot of tag-related things we could do with the tags command and/or other commands with --pivot, but it's not clear what. PRs or further discussion are welcome, and should probably come with real-world use cases to motivate them.
