### ISSUE TITLE
Irrational number with 255 decimal places shown when using the print command.

### ISSUE THREAD

**Issue by maisammusthafa** [simonmichael/hledger#262]
I ran into a weird issue when I used the print command on ledger files like this one: http://vpaste.net/PNgdB
The output shows the currency conversion rate as an irrational number with a lot of decimal places (255 decimal places, to be exact)!
I'm using hledger 0.25 on Windows.
![screenshot](https://cloud.githubusercontent.com/assets/8976853/7787221/9085ea34-0219-11e5-81e6-d4421516312f.png)

**Comment by simonmichael** [comment]
Interesting!

It calculates the conversion rate as (160 + 160) / (10 + 11), which is indeed 15.238095238095...
And unlike regular amounts, when rendering price amounts I believe there's no amount style to limit the rendering precision. So it prints as many decimal places as it can which with the current decimal-based implementation apparently means 255. (The old double-based implementation gave 15 decimal places,)

Price amounts were deliberately given unlimited precision because conversion rates tend to need a higher precision than the amounts being converted.

What would be better for it to do here ? Should we set a hard limit on the rendering precision, like 15 decimal places ?

**Comment by maisammusthafa** [comment]
I think it's best to display the total price instead of the rate. That is how it's done in the first two transactions of the above example too.

Printing "USD 11.00 @@ MVR 160.00" certainly looks better than using high precision decimals to represent the rate. Besides, I think showing exact amounts is more useful than showing a rounded decimal value.

**Comment by simonmichael** [comment]
Ledger just doesn't print the conversion price at all in this case.

**Comment by maisammusthafa** [comment]
Yeah, that's a good idea too. Not print a price or rate at all.

**Comment by simonmichael** [comment]
So that's the easiest option. But it would be a little inconsistent, as current behaviour of hledger print is to always show any conversion rates in effect.

With price precision hard-coded to 15, this example looks like:
```
2015/01/01 Transaction ONE and TWO combined.
    Assets:Cash USD  USD 10.00 @ MVR 15.238095238095238
    Assets:Cash MVR   MVR -160.00
    Assets:Cash USD  USD 11.00 @ MVR 15.238095238095238
    Assets:Cash MVR   MVR -160.00
```

When there is only one posting in each commodity, it does use a total price (@@) for brevity, but in this example with multiple postings in each commodity, it's not so easy to do that. I guess it would have to be:
```
2015/01/01 Transaction ONE and TWO combined.
    Assets:Cash USD  USD 10.00 @@ MVR 152.38095238095238
    Assets:Cash MVR   MVR -160.00
    Assets:Cash USD  USD 11.00 @@ MVR 167.61904761904762
    Assets:Cash MVR   MVR -160.00
```

**Comment by maisammusthafa** [comment]
Hmm.. The third one looks best, but since it's not that easy to do, I would suggest the first one.

The first one isn't weird, because it still shows a meaningful value (15.238095238095238, the average rate of the postings).

The second one, on the other hand, is very weird since it shows the average rate multiplied by the amount, which is what... Average total? 152.38095238095238 and167.61904761904762 doesn't really tell you anything. It's a meaningless value.

**Comment by maisammusthafa** [comment]
So, I guess it will have to be with the rate precision hard-coded to 15.


2015/01/01 Transaction ONE and TWO combined.
    Assets:Cash USD  USD 10.00 @ MVR 15.238095238095238
    Assets:Cash MVR   MVR -160.00
    Assets:Cash USD  USD 11.00 @ MVR 15.238095238095238
    Assets:Cash MVR   MVR -160.00

**Comment by simonmichael** [comment]
Or, to minimize excessive precision, it could be based on the precision of the amounts being converted. 

Eg, the sum of their precisions. In the example above USD's precision is 2, MVR's is 2, so the generated price would have 4, which looks a bit nicer:
```
2015/01/01 Transaction ONE and TWO combined.
    Assets:Cash USD  USD 10.00 @ MVR 15.2381
    Assets:Cash MVR   MVR -160.00
    Assets:Cash USD  USD 11.00 @ MVR 15.2381
    Assets:Cash MVR   MVR -160.00
```
Is this a good idea ? I'm not sure.

**Comment by maisammusthafa** [comment]
Sounds good. I remember reading about ledger doing the same thing to handle precision. It's in the ledger documentation.

**Comment by simonmichael** [comment]
I've implemented the last approach, described in the commit. I believe this should make it work reasonably in all cases, any testing welcome.
