### ISSUE TITLE
hledger-ui/hledger-web --real does not reflect nonvirtual credit

### ISSUE THREAD

**Issue by Artiavis** [simonmichael/hledger#354]
I started off my hledger journal using virtual transactions for budgeting purposes, and stopped after a while. I noticed, however, that when I use a virtual posting to the same account as an actual posting, and use the real flag, the actual posting shows up with the credit netted between the virtual and nonvirtual postings.

```
2016/04/01 Parking Bill
    expenses:auto:parking           100
    assets:checking                -100
    [assets:checking]               100
    [budget:auto:parking]          -100
```

Results in the following line-item entry in the hledger-ui mode (and something similar in hledger-web):

`2016/04/01 Parking Bill      ex:au:parking               0    (Same as previous balance)`.

However, hledger itself does correctly exclude the virtual posting and credits

`2016/04/01 Parking Bill        assets:checking         100   100`.

I don't think I'm doing anything wrong here, but if I am, please show me where I'm going astray. I really want to use hledger-ui as part of my workflow since it would be much quicker and less error-prone than querying against hledger constantly, but I can't until this bug is fixed/worked around.

**Comment by simonmichael** [comment]
I see what you mean, thanks for the bug report.

The hledger-ui bug has now been fixed in master, and also you can now toggle real mode with R (with a limitation/bug: toggling real postings in the transaction screen only works if the previous register screen was not in real mode).

I'm not sure if this fix has made any difference to hledger-web, which currently ignores command-line flags like -R/--real I believe. If you see any change, let me know.

**Comment by simonmichael** [comment]
(on the new issue which I'll create for hledger-web now).

**Comment by simonmichael** [comment]
This is now resolved for hledger-ui I believe. Toggling real mode on the transaction screen was fixed, but I disabled it in favour of always showing the full unfiltered transaction.
