### ISSUE TITLE
Importing data

### ISSUE THREAD

**Issue by ccorcos** [simonmichael/hledger#374]
Are there any integrations for importing data into hledger? I particular, I'm not excited about typing out my credit card bill in hledger every month...

**Comment by simonmichael** [comment]
http://hledger.org/csv.html is how I do it. Also a number of the tools at http://plaintextaccounting.org/#data-importconversion can be used. ledger-autosync is a good one if you have OFX Direct access set up at your bank.

**Comment by simonmichael** [comment]
PS, but if all else fails, type it out! :) This is an effective way to feel your spending and to limit credit card use.

**Comment by ccorcos** [comment]
Awesome thanks for the links! I just learned all about OFX. Looks pretty sweet other than storing your bank information without encryption...

The real question now is what am I really gaining from using this... :/

**Comment by simonmichael** [comment]
I just wrote a little about that at https://news.ycombinator.com/item?id=12124890

**Comment by simonmichael** [comment]
PS and I'd like to come up with better answers to that, feel free to discuss further on [irc](http://irc.hledger.org) or [mail list](http://list.hledger.org).

**Comment by ccorcos** [comment]
cool! i suppose I'm interested for just general awareness of my funds. it would be nice if I could track certain expenditures a lot easier and see them plotted out on a graph or at least view the totals in a chart...

**Comment by simonmichael** [comment]
I won't post further here, but since I was just now working on these: here are some typical accounting questions and hledger reports:

* balance sheet
** what are my liquid assets now
hledger bal assets not:receivable
** what have they been by month
hledger bal assets not:receivable -H -M
** what are all my assets and liabilities now
hledger bal '(assets|liabilities)'
** what have they been by month
hledger bal '(assets|liabilities)' -H -M

* cashflow statement
** what has been my cashflow by month
hledger bal assets not:receivable -M

* income statement
** what have my revenues been by month
hledger bal revenues -M
** what have my total expenses been by month
hledger bal expenses -M
** what are my monthly fixed expenses
** what are my less frequent fixed expenses
** what have my non-fixed expenses been
** what has my net profit/loss been by month
hledger bal '(revenues|expenses)' -M

* budgeting
** what is current standing with respect to budgets (month, year etc.)
** what is average monthly expense in each budget category
** what is average monthly outflow from each budget envelope
** what is average monthly cashflow of each budget envelope

* forecasting
** for periods
*** rest of month
*** next 3 months
*** rest of year
** what are my expected revenues
** what are my expected expenses
** what are my expected profits/losses
** what are my expected cashflows
** what are my expected assets
** what are my expected liabilities

**Comment by ccorcos** [comment]
So fixed expenses is quite interesting. Sometime I pay 2-3 months of rent at a time. So that may be a little finicky. Forcasting sounds amazing though!
