### ISSUE TITLE
download: installing on arch...

### ISSUE THREAD

**Issue by egils-verkstad** [simonmichael/hledger#434]
I tried installing on Arch and tried to document my efforts for the benefit of others interesting in a stable hledger install.
I recommend adding the following to the download-page:

> On arch install the stable version with 
> `sudo pacman -S stack ghc && stack setup && stack install --resolver=nightly hledger hledger-ui hledger-web`
> or the dev-version via the AUR-package `hledger-git`

---
Running "stack setup" produces an error if GHC is not installed already.

```
   $ stack setup
  Run from outside a project, using implicit global project config
  Using resolver: lts-7.9 from implicit global project's config file: /home/egil/.stack/global-project/stack.yaml
  Unable to find installation URLs for OS key: linux32-ncurses6

```

**Comment by simonmichael** [comment]
Thanks! Do you know if the stack setup failure has been reported to the stack tracker ?

There is a question about whether to include stack setup in the command line. We recently removed it from the source instructions, instead saying "run stack setup if stack install tells you to", because doing it preemptively that way won't necessarily get you the required GHC version, so the user would gets another request to run stack setup and have to do it a second time (or something like that, there was confusion).

**Comment by simonmichael** [comment]
Plus, since you have installed ghc with pacman, won't stack install use it automatically, requiring no stack setup step ?

**Comment by simonmichael** [comment]
I will add hledger-api to the command line, unless there's some reason you left it out.

**Comment by simonmichael** [comment]
And... hmm, this command does not install a packaged version, so probably doesn't belong in the top section. Perhaps it should be mentioned somewhere in the installing from source section.

**Comment by simonmichael** [comment]
Linked this issue from B1.

**Comment by simonmichael** [comment]
@egils-verkstad, @mstksg, Arch users: do you think the "On Arch, you may need to also install GHC manually" note is still needed at http://hledger.org/download.html#b ?
