### ISSUE TITLE
command line parse errors include ugly stack trace

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#529]
Since GHC 8, calls to error show a stack trace by default. We fixed this for most hledger errors but command line errors still have the problem, we are waiting on https://github.com/ndmitchell/cmdargs/issues/42:
```
$ hledger bs -M --pretty
hledger: Unknown flag: --pretty
CallStack (from HasCallStack):
  error, called at ./System/Console/CmdArgs/Explicit.hs:143:15 in cmdargs-0.10.14-39NpGO5c3XuHJDHZnfj5mm:System.Console.CmdArgs.Explicit
```

**Comment by simonmichael** [comment]
Bounty added to that issue, add yours if this bugs you too.

**Comment by ndmitchell** [comment]
The problem is you are calling `processValue`, which is essentially `process` but with an error on the `Left`. See https://hackage.haskell.org/package/cmdargs-0.10.16/docs/src/System-Console-CmdArgs-Explicit.html#processValue

I suspect you might get better results if you were to handle the error yourself doing:

```
case process m args of
     Left x -> do hPutStrLn stderr x; exitFailure
     Right x -> return x
```

Should I add a `processValueIO` that does that? My guess is that `processValue` will never present exactly the UI you want.

**Comment by ndmitchell** [comment]
As of `cmdargs-0.10.17` the function `processValue` now calls `errorWithoutStackTrace`. However, if you are in IO, I recommend `processValueIO` which prints the error to stderr and throws ExitFailure, which is usually a better option.
