### ISSUE TITLE
--date2 does not show the auxiliary date

### ISSUE THREAD

**Issue by benjamin-thomas** [simonmichael/hledger#604]
Version: hledger-ui 1.3

---

Hello,

Great job on your apps, very much enjoying exploring the different possibilities offered here...

I stumbled upon a little hiccup though. The manual states:

```manual
  --date2               show, and make -b/-e/-p/date: match, secondary
                           dates instead
```

However, given the following ledger file

```ledger
2017/01/01 Opening Balance
    Assets:CheckingAccount                      100€
    Equity:OpeningBalance

2017/01/02=2017/01/03 Supermarket
    Expenses:Food:Groceries                      40€
    Assets:CheckingAccount
```

 The following commands display the same dates:

```console
hledger-ui -f ~/test.ledger
hledger-ui -f ~/test.ledger --date2
```

Meaninng, for the Supermarket entry, I would expect `2017/01/03` to be displayed with the `--date2` flag.

Any thoughts?

**Comment by simonmichael** [comment]
Thanks @benjamin-thomas. You're right, hledger-ui doesn't seem to pay much (any ?) attention to --date2.

General flags like this aren't required to have an effect on every single command. I know --date2 affects the output of the register command, but otherwise I think it mainly affects date matching. Perhaps the wording of its help could be improved. 

As for making it affect hledger-ui - I would consider a PR, but I don't think it's needed. I consider --date2 and secondary dates to be a misfeature actually, and always recommend overriding posting dates instead.

**Comment by benjamin-thomas** [comment]
Thanks for the detailed feedback!

Yes the wording is a little ambiguous, but then again there are quite a lot of features.

I'd love to dig in, but being unfamiliar with Haskell, it's not very realistic for me at the moment.

Overriding post dates seems much better, thanks!

Closing this, since it was a misunderstanding on my part.

**Comment by simonmichael** [comment]
Thanks for the report. As a minimal fix, I'm thinking

    --date2               make -b/-e/-p/date: match secondary dates instead; make register show secondary date

**Comment by benjamin-thomas** [comment]
Yeah this seems better to me!

Keep on the great work :)
