### ISSUE TITLE
Unable to install hledger-api-1.5 from stack / clarify install docs

### ISSUE THREAD

**Issue by varac** [simonmichael/hledger#690]
I tried to follow the installation docs to install hledger-api-1.5 using stack, but it cannot install all dependencies: 

```
» stack install hledger-lib-1.5 hledger-1.5 hledger-ui-1.5 hledger-api-1.5 hledger-web-1.5
Run from outside a project, using implicit global project config
Using resolver: lts-8.17 from implicit global project's config file: /home/varac/.stack/global-project/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      servant-server: needed (>=0.10), 0.9.1.1 found (latest applicable is 0.12)
    needed for package hledger-api-1.5
```

All other packages can get installed fine (I tried afterwards without hledger-api-1.5).

**Comment by simonmichael** [comment]
I am guessing your resolver is too old, try adding —resolver lts-10.3. 

It’s hard to make foolproof install instructions, but suggestions welcome. The hledger-install script should also work for you.

**Comment by varac** [comment]
Hmm, with `resolver: lts-10.3` in my `stack.yaml` I now get this:

```
» stack install hledger-api-1.5
Run from outside a project, using implicit global project config
Using resolver: lts-10.3 from implicit global project's config file: /home/varac/.stack/global-project/stack.yaml
Downloaded lts-10.3 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags: failed to parse field packages: failed to parse field constraints: failed to parse field flags: Invalid flag name: \"bytestring--lt-0_10_4\""
```

Sorry, I'm an absolute haskell/stack noob.

**Comment by simonmichael** [comment]
What I do is search for those error messages, and this one looks a bit like https://github.com/commercialhaskell/stack/issues/3686 . I think "stack upgrade" is the right course here.

**Comment by varac** [comment]
@simonmichael thx, that brought me further. Still, I'm now getting this:

```
--- ~ » stack install hledger-api-1.5                                                                                                             
Preparing to install GHC (nopie) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-nopie-8.2.2.                                      
Installed GHC.                                                                       
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading root                                                                                 
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
Downloading snapshot                                                                             
Downloading mirrors                                                                              
Cannot update index (no local copy)                                                              
Downloading index                                                                                
Updated package index downloaded                                                                 
Update complete                                                                                  
Populated index cache.    

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hledger-api-1.5:
    hledger-1.4 from stack configuration does not match >=1.5 && <1.6 (latest matching version is 1.5)
    hledger-lib-1.4 from stack configuration does not match >=1.5 && <1.6 (latest matching version is 1.5)
needed since hledger-api is a build target.

Some potential ways to resolve this:

  * Recommended action: try adding the following to your extra-deps in /home/varac/.stack/global-project/stack.yaml:

- hledger-1.5
- hledger-lib-1.5

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * You may also want to try using the 'stack solver' command.

Plan construction failed.
```

**Comment by jeevcat** [comment]
Try with the full command again:
 `stack install hledger-lib-1.5 hledger-1.5 hledger-ui-1.5 hledger-api-1.5 hledger-web-1.5`

If that doesn't work try deleting your `~\.stack` folder to clear stack's config. Then do a `stack upgrade` again, then try installing with the above command again.

**Comment by varac** [comment]
@jeevcat Thx, after installing all packages together it's working now !

**Comment by simonmichael** [comment]
@varac, thanks for these reports. I think this shows that 

1. the download page's "stack install hledger-lib-X hledger-X hledger-ui-X hledger-web-X hledger-api-X" is unreliable: it depends on the user's default stackage snapshot, because stack will go to hackage when necessary to find the hledger-*-X packages, but not to find their deps (servant-server above). Or that's how I read it.

2. if you try to stack install a hledger-*-X is not in the snapshot being used, you have to specify all the other hledger packages it depends on in the install command, and this needs to be made clearer.

3. at least when using stack, we need to more strongly encourage using the latest version of it, because it is very often the cure for breakages in the ecosystem (the cassava flag problem above).

For 1, we have to ensure that the installer is using a sufficiently recent/tested snapshot. And I don't want to have to keep changing the install command over time as hledger releases progress through the snapshots. The easiest thing to do is recommend `--resolver nightly`. This maximises the chance of success, but also the time and energy spent building deps. Perhaps with a note suggesting to relax or drop this option to try saving build time.

For 3, should hledger-install should always do a stack upgrade before running stack ?
