### ISSUE TITLE
An invertible way to turn a journal into a String

### ISSUE THREAD

**Issue by NorfairKing** [simonmichael/hledger#707]
Prompted by https://github.com/simonmichael/hledger/issues/701, it would be nice to be able to generate those commodity directives. However, it would be a lot simpler to just be able to generate a complete journal and then write it.
I don't think there is currently a way to do that. 
Would this be something you would be interested in building?

**Comment by simonmichael** [comment]
I don't follow, can you give an example ?

**Comment by ony** [comment]
Purpose of `commodity` directive is to declare single format that should be used for displaying and sometimes interpreting numbers.

It is possible to generate that directive out of existing journal based on inferred styles for commodities. Problem is that usually it is not something that you want. For example in case of #701 it will produce precision which is 53-digits long. Though the problem you see with `--value` is caused by leaking inter-commodity price styles into real amounts and still worth of fixing, I guess.

The only case when it might be useful is to help correctly interpret ambiguities like `$1.00` vs `$1,000` using information from numbers like `$2,199.99`. But instead of producing "intermediate" journal for future processing by `hledger` it is better to have original parser to get 2 passes internally and even benefit from unsolvable inconsistencies.

**Comment by simonmichael** [comment]
Inactive, closing for now.
