### ISSUE TITLE
vague amount parse error message

### ISSUE THREAD

**Issue by jungle-boogie** [simonmichael/hledger#747]
Hello Simon!

I would like to track how many gallons purchased per fuel transaction. Using the commodities function is a simple way to do so. However, if I forget the important `@`, the error message generated by hledger doesn't make it clear of the mistake.

```
$ cat fuel.ledger
2018/04/01 * Fuel
    Expenses:Auto:2018:Fuel         51.170 gallons $1.999
    Assets:Cash:Wallet
```

```
$ hledger -f fuel.ledger bal
hledger: /home/simon/finance/fuel.ledger:2:5:
unexpected 'E'
expecting newline
```

When compared to ledger, the result isn't exactly perfect. but it doesn't complain about expecting new line:
```
$ ledger -f fuel.ledger bal
While parsing file "/home/simon/finance/fuel.ledger", line 2:
While parsing posting:
  Expenses:Auto:2018:Fuel         51.170 gallons $1.999
                                  ^^^^^^^^^^^^^^^^^^^^^
Error: Unexpected char '$' (Note: inline math requires parentheses)
```

I don't know if others have encountered this before.

**Comment by simonmichael** [comment]
Good example, I would love to get some patches improving those parse errors.

**Comment by simonmichael** [comment]
Possibly useful things:
- https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Read/Common.hs#L432
- http://hackage.haskell.org/package/megaparsec lots of tricky parsing/error control functions in the api
- https://markkarpov.com/megaparsec/custom-error-messages.html
- https://markkarpov.com/megaparsec/fun-with-the-recovery-feature.html
-

**Comment by awjchen** [comment]
Hi there, I'd like to try to help with this issue. This is my first time trying to contribute to open source, so please feel free to point out anything I could be doing better!

I'm also not very experienced with programming, so perhaps I might not be able to resolve this issue. Extending the current parser with custom error messages is very daunting for me, and not something I would yet attempt. But I think the following might represent an incremental improvement to the current parse error.

In `JournalReader.hs`, I've reduced the scope of a `try` statement in `postingsp` by moving it into the first part of `postingp`: after an account is successfuly parsed, we commit to parsing a posting in order to restrict backtracking on failure.

```haskell
diff --git a/hledger-lib/Hledger/Read/JournalReader.hs b/hledger-lib/Hledger/Read/JournalReader.hs
index a42d7be8..16246f3c 100644
--- a/hledger-lib/Hledger/Read/JournalReader.hs
+++ b/hledger-lib/Hledger/Read/JournalReader.hs
@@ -581,7 +581,7 @@ test_transactionp = do
 -- Parse the following whitespace-beginning lines as postings, posting
 -- tags, and/or comments (inferring year, if needed, from the given date).
 postingsp :: MonadIO m => Maybe Day -> ErroringJournalParser m [Posting]
-postingsp mdate = many (try $ postingp mdate) <?> "postings"
+postingsp mdate = many (postingp mdate) <?> "postings"
 
 -- linebeginningwithspaces :: Monad m => JournalParser m String
 -- linebeginningwithspaces = do
@@ -593,10 +593,12 @@ postingsp mdate = many (try $ postingp mdate) <?> "postings"
 postingp :: MonadIO m => Maybe Day -> ErroringJournalParser m Posting
 postingp mtdate = do
   -- pdbg 0 "postingp"
-  lift (skipSome spacenonewline)
-  status <- lift statusp
-  lift (skipMany spacenonewline)
-  account <- modifiedaccountnamep
+  (status, account) <- try $ do
+    lift (skipSome spacenonewline)
+    status <- lift statusp
+    lift (skipMany spacenonewline)
+    account <- modifiedaccountnamep
+    pure (status, account)
   let (ptype, account') = (accountNamePostingType account, textUnbracket account)
   amount <- spaceandamountormissingp
   massertion <- partialbalanceassertionp
```
This brings the parse error for the `fuel.hledger` example closer to that of ledger.
```
$ hledger -f fuel.hledger bal
hledger: /home/alex/personal/hledger/fuel.hledger:2:52:
unexpected '$'
expecting ';' or newline
```
The change passes the tests, but I'm not sure how to tell if I've unexpectedly broken something.

**Comment by simonmichael** [comment]
Hi @awjchen, I'm very happy you picked us for your first FOSS contribution. That looks great, would you like to fork the repo, commit this change, and create a pull request ? If you need help, ask here or on #hledger IRC channel (github also has good help).

**Comment by awjchen** [comment]
I've prepared the pull request!

**Comment by simonmichael** [comment]
Thank you very much! 

I guess this specific issue can be closed.
