### ISSUE TITLE
Treacherous multi-currency auto-inference

### ISSUE THREAD

**Issue by Ekleog** [simonmichael/hledger#758]
With eg. the following ledger file:
```
D 1,000.00€
 
2018-05-08 * test
    expenses:foo  $3
    assets  -3
```

The transaction is balanced to be $3 / -3€. Which sounds treacherous to me.

I think auto-inference could be straight-out removed, as the previous example could be rewritten with the more error-free:
```
D 1,000.00€
 
2018-05-08 * test
    expenses:foo  $3 @@ 3€
    assets
```

What do you think about it?

**Comment by wad209** [comment]
Personal opinion, this is the correct behavior. The default should apply to any unannotated unit. Maybe we could implement some kind of warnings for this instead?

**Comment by Ekleog** [comment]
Oh I didn't explain clearly the issue I was thinking of. I do think the default should apply to any unannotated unit indeed. The issue I was considering is actually larger than this example: I think the following shouldn't balance (for the reason mentioned above of being treacherous in some cases):
```
2018-05-08 * test
    expenses:foo  $3
    assets  3€
```

BTW, another example was raised on IRC by @aszlig: intuitively, the market price is what would be used to balance such transactions (the fact that the manual states it's not what is done being in my humble opinion irrelevant to the fact that it's unintuitive). So this could lead to people writing such a transaction and thinking “oh alright I've bought it at market price”, not noticing the price was actually inferred and not verified in any way.

**Comment by simonmichael** [comment]
Thanks for the feedback. +1 catchy issue name!

Re your last point, Ledger does the opposite of what you find intuitive above - it infers a new market price from a transaction like that. I found this hard to learn and tried to simplify it by making a clear distinction between (one-time, fixed) transaction prices and (ambient, fluctuating) market prices.

I do think you should bring this up on the mail list as well, as most users won't see this, and changing the long-established behaviour needs wider discussion.

**Comment by simonmichael** [comment]
> First of all, we will require that all transactions in the ledger are
> balanced. Hledger currently checks this for transactions containing
> only one commodity, but not when multiple commodities are included in
> the transaction. One way to do this in a way that is
> backwards-compatible is to introduce a new account named UNBALANCED,
> and then to use this account to balance each transaction when
> generating reports. For instance, consider the following transaction:
> 
> 2019-04-01 Buy stocks
>     assets:cash          -$1000
>     assets:investments  1 AAPL
> 
> This transaction is currently unbalanced, since the amounts sum up to
> -$1000, and 1 AAPL. 

I guess Ledger/hledger use that word differently.. they consider the
above to be syntactic sugar for the following transaction, which they
call balanced:

    2019-04-01 Buy stocks
        assets:cash                   -$1000
        assets:investments   1 AAPL @@ $1000

> When generating reports, this transaction would be
> turned into this:
> 
> 2019-04-01 Buy stocks
>     assets:cash         -$1000
>     assets:investments  1 AAPL
>     UNBALANCED           $1000
>     UNBALANCED         -1 AAPL

> An additional flag (--force-balanced or similar) could be introduced.
> When activated, this checks that all transactions are balanced, and if
> not gives an error message. To avoid this error message, the user would need to make explicit
> trading accounts, for instance as follows:
> 
> 2019-04-01 Buy stocks
>     assets:cash         -$1000
>     assets:investments  1 AAPL
>     trading              $1000
>     trading            -1 AAPL

Related to #758, "Treacherous multi-currency auto-inference".

> Balance sheets
> 
> - The command bal -M -V -H should do exactly what bal -M -V -H
>   --value-at=period currently does.
> 
> - The command bal -M -V should first compute bal -M -V -H
>   --value-at=period, and then display the differences in balance for
>   each period. The interpretation should be that this command shows
>   the changes in balance for each period. This interpretation
>   currently holds when -V is not used, and should also hold when -V is
>   used.
> 
> All questions we may have about the performance of our investments may
> be answered by looking at the balances (historical or changes) of the
> trading account and the assets:investments account. 

I'm too long away from the code to comment on this in detail; maybe later.

> Print / register
> 
> The print / register commands show individual transactions. When -V is
> used, additional valuation transactions need to be generated to
> account for changes in valuations. This may be done as follows. First
> we convert all transaction postings to the base currency at the date
> of the transfer. For our example above, we would get the transaction.
> 
> 2019-04-01 Buy stocks
>     assets:cash         -$1000
>     assets:investments   $1000
>     trading              $1000
>     trading             -$1000

This has been my original thought too - model revaluation in depth, ie as
transaction events, and let the reports do their thing. I called this 
"bottom up" before.

Then there is the "top down", shortcut method where we would only
calculate the revaluations where needed, ie in balance reports. This
way the calculation is simpler, you calculate only for the accounts
and periods being shown in the balance report.

Calculating for every account, depending on which commodities it
holds, potentially at every price change, sounds like a lot of work.
Though, it might be that the two methods work out equally efficient
due to laziness.

Including revaluations in balance and register reports is necessary to
keep the accounting equation satisfied. Showing revaluation events in
print reports isn't strictly necessary, though it does sound nice for
consistency, understanding, and troubleshooting.

> The two trading postings add up to zero, so this transaction should be
> displayed as
> 
> 2019-04-01 Buy stocks
>     assets:cash         -$1000
>     assets:investments   $1000

Hiding postings written explicitly in the journal would be quite a new
behaviour for print.

> Now, for each commodity valuation, for instance P 2019-04-10 AAPL
> $1200, we add a transaction
> 
> 2019-04-10 Valuation: AAPL $1200
>     assets:investments   $200
>     trading             -$200
> 
> This transaction involves all accounts that have a non-zero balance of
> AAPL, and corrects the balance of each account with the updated price.
> This may result in a lot of valuation transactions, so if we want to
> we may add a flag --price-frequency which takes a period (daily,
> weekly, monthly, quarterly, or yearly) as argument. When this flag is
> used, the marked prices are filtered so that there are a maximum of
> one commodity valuation per period.

In non-periodic balance reports, one revaluation for the whole report
period is enough.

In periodic register/balance reports, the periods are a natural
interval for revaluations.

In print reports and non-periodic register reports, there's no
obvious frequency or date at which to insert revaluations. It could be
as specified by a new flag as you say, or once at the end, or (in the
case of print) as specified by -D/W/M/Q/Y.

**Comment by simonmichael** [comment]
Oh shoot, wrong issue. Reposting.

**Comment by simonmichael** [comment]
See also: #1177.

**Comment by Xitian9** [comment]
Ever since 0f1837816dd26055767fe524d483df5c2c091b8b we now have a way of addressing this. Calling hledger with `--strict` will not auto-infer prices in these cases. Furthermore, calling `hledger check balancednoautoconversion` will also check for these. I think this issue can be closed.
