### ISSUE TITLE
Headings for Monthly reports --> Name versus ISO 8601

### ISSUE THREAD

**Issue by JalapenoGremlin** [simonmichael/hledger#766]
I apologize if this is the incorrect place to report/ask about this. 

In hledger 1.9 the Month headers changed from 2018/01 to "Jan". (and were sorted alphabetically, so Apr came before Jan --  but that appears to be fixed in master ( #742)). 

Is there anyway to still get the YYYY/MM format?

|    | Jan | Feb | Mar | ... | Jan | Feb | ... | Jan | Feb |
|----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| A: | 3.1 | 2.3 | 3.3 | ... |     |     |     |     |     |

This fomat is difficult especially in budgets that extend for "some long intervals" -- emacs allows long lines in my usage and I sort of lose track as to how far right/left I've traversed.

1. I guess this is a "feature request" to allow the "monthly grouping display format" to be specified.
2. I'm new to ledger/hledger (and Haskell is all Greek to me at this point) so if such an option exists, apologies in advance. 
3. If there is a more suitable location for discourse on such topics (rather than the issue tracker at github), please let me know. 
4. Thanks for all the work on hledger.

**Comment by simonmichael** [comment]
Thanks for the report. You're right about hledger 1.9's balance --budget report headings, it is fixed in hledger 1.9.1. And, good point about the month name headings! I never thought of that. 
What would be the best resolution ? Some options:

1. revert to old behaviour, always show `YYYY/MM`
2. always show `Mon YYYY`
3. show `Mon` when only one year is involved, otherwise `Mon YYYY`
4. show `Mon YYYY` for the first month shown in each year, `Mon` for the rest (different column widths)
5. add support for a custom --period-format (?) option
6. 5 plus one of the others

**Comment by jungle-boogie** [comment]
My preference would be option 1.

**Comment by JalapenoGremlin** [comment]
My initial thought was to "have a default" (I'm not committed to one format or another -- option 1 or option 2 or the current behavior), with the ability to specify a `--period-format "%Y/%M"` (maybe use the % modifiers from `date`?) . Picking the "default" will invariably upset some people -- "I like the old way, I like the current way, I like something else, [you're breaking my workflow](https://xkcd.com/1172/)  ;)"
Of course, the columns would still need to be sorted by actual time period and not lexicographical by the display form. 

No idea the complexity of such a fix. Maybe hledger is a good reason to "Learn Me a Haskell for Great Good!"

Thanks for your help.

**Comment by Xitian9** [comment]
I think this was resolved by f518da747ccac338be26b5ab3bdc11bfc7bbb375, and this can now be closed.
