### ISSUE TITLE
Hledger does not detect cycles when resolving 'include' directives

### ISSUE THREAD

**Issue by jbweston** [simonmichael/hledger#853]
Brought up by @simonmichael in #846,  [here](https://github.com/simonmichael/hledger/pull/846#pullrequestreview-139763653).

### Steps to Reproduce
```
$ echo 'include b.journal' > a.journal
$ echo 'include a.journal' > b.journal
$ hledger -f a.journal print
```

### Observed Behaviour
Hledger runs until it runs out of memory. This is also a bug in ledger, except that it fails due to too many open file handles long before it exhausts the available memory.

### Expected Behaviour
There are only 2 possibilities AFAICT: an error should be reported, or the `include` directive that would result in a cycle being formed should be ignored (because we're already parsing the file in question). I think it is reasonable to expect people to "break" cycles manually, and so reporting an error is the correct thing to do.

**Comment by jbweston** [comment]
My first idea about how to solve this is to keep a list of files that represents the stack of `include` directives. 

Each time we process an `include` directive we first check whether the file we are including is in the stack. If it is, we handle the cycle creation (error or ignore, as discussed in the issue description), if it is not we push the current filename onto the stack, parse the file specified by the `include`, and pop from the stack afterwards.

This has `O(N)` space and time complexity for storing and traversing the stack (to determine if we are going to form a cycle), where `N` is the "depth" of `include`s. I would not expect `N` to exceed 100 (in practice I would imagine that it is < 10), so I think that this is probably fine.

The only thing that I am unsure of is technically where to add this stack. Should it be somehow stored in the parser? I do not know if it is possible to store arbitrary metadata in the parser, and whether this is good design.

**Comment by simonmichael** [comment]
@jbweston: sounds great. Yes, you can store this data in the state we keep during parsing. Take a look at Journal in Types.js. Maybe add a jparseparentfiles field or something.

**Comment by simonmichael** [comment]
I merged #857, but something seems not quite right with parsing:
```
# a cycle of three files:
$ cat a.j
include b.j
$ cat b.j
include c.j
$ cat c.j
include a.j
# reading a.j (or c.j) gives a fairly understandable error:
$ hledger stats -f a.j
hledger: in file included from /Users/simon/src/PLAINTEXTACCOUNTING/hledger/a.j:1:12,
in file included from /Users/simon/src/PLAINTEXTACCOUNTING/hledger/b.j:1:12,
/Users/simon/src/PLAINTEXTACCOUNTING/hledger/c.j:1:12:
  |
1 | include a.j
  |            ^
Cyclic include: /Users/simon/src/PLAINTEXTACCOUNTING/hledger/a.j

# but reading b.j gives an unexpected parse error:
$ hledger stats -f b.j
hledger: in file included from /Users/simon/src/PLAINTEXTACCOUNTING/hledger/b.j:1:12,
/Users/simon/src/PLAINTEXTACCOUNTING/hledger/c.j:1:2:
  |
1 | include a.j
  |  ^
unexpected 'n'
```

**Comment by jbweston** [comment]
This is indeed very spooky; I can't see how there's enough "room" in  [the diff](https://github.com/simonmichael/hledger/pull/857/files) for such a class of bug to creep in...

**Comment by jbweston** [comment]
It's also strange because of the "symmetry" between the 3 files; why does this only manifest when reading `b.j` and not `a.j` or `c.j`?

The plot thickens:

```
$ cat a.j 
include x.j
$ cat x.j
include c.j
$ cat c.j
include a.j
$ hledger stats -f a.j
hledger: in file included from /home/jbw/priv/code/2018/hledger/a.j:1:12,
/home/jbw/priv/code/2018/hledger/x.j:1:2:
  |
1 | include c.j
  |  ^
unexpected 'n'

$ hledger stats -f x.j
hledger: in file included from /home/jbw/priv/code/2018/hledger/x.j:1:12,
/home/jbw/priv/code/2018/hledger/c.j:1:2:
  |
1 | include a.j
  |  ^
unexpected 'n'

$ hledger stats -f c.j
hledger: in file included from /home/jbw/priv/code/2018/hledger/c.j:1:12,
in file included from /home/jbw/priv/code/2018/hledger/a.j:1:12,
/home/jbw/priv/code/2018/hledger/x.j:1:12:
  |
1 | include c.j
  |            ^
Cyclic include: /home/jbw/priv/code/2018/hledger/c.j
```

**Comment by jbweston** [comment]
I renamed `b.j` to `x.j`, and modified `a.j` so that it has only `include x.j`, and now the `unexpected 'n'` appears when running `hledger` on `a.j` too!

**Comment by jbweston** [comment]
Ok I just applied the following diff on aab7d2d96 (the commit before the commit set for #846), and I see the same behavior as on `master`, so we can be sure that the bug is not due to some weird transformation I've done as part of #846.

```
diff --git a/hledger-lib/Hledger/Read/JournalReader.hs b/hledger-lib/Hledger/Read/JournalReader.hs
index 31102024..39742bc8 100644
--- a/hledger-lib/Hledger/Read/JournalReader.hs
+++ b/hledger-lib/Hledger/Read/JournalReader.hs
@@ -201,6 +201,11 @@ includedirectivep = do
   -- read child input
   let curdir = takeDirectory (sourceName parentpos)
   filepath <- lift $ expandPath curdir filename `orRethrowIOError` (show parentpos ++ " locating " ++ filename)
+
+  parentfilestack <- fmap sourceName . statePos <$> getParserState
+  when (filepath `elem` parentfilestack)
+    $ parseErrorAt parentpos ("Cyclic include: " ++ filepath)
+
   childInput <- lift $ readFilePortably filepath `orRethrowIOError` (show parentpos ++ " reading " ++ filepath)
 
   -- set child state
```

**Comment by simonmichael** [comment]
It might be useful to trace things in includedirectivep, which recently changed to support wildcards.

**Comment by jbweston** [comment]
> It might be useful to trace things in includedirectivep, which recently changed to support wildcards.

I also applied the changes that I made to `includedirectivep` to detect cycles to aab7d2d (which was the commit *before* all the changes to support wildcards) and the bug *still* shows up.

This indicates that the bug is independent of the changes that were done to support wildcards.

**Comment by jbweston** [comment]
My findings so far:

When I replace `parseErrorAt parentpos ("Cyclic include: " ++ filepath)` with `undefined` then hledger crashes when running on any of the files in the cycle. If I break the cycle by commenting out the `include` line in any single file, then `hledger` exits cleanly.

This indicates that the cycle is being detected correctly, but something weird is happening when the error from `parseErrorAt` is propagated back up.

@simonmichael what's the correct way to enable tracing in the parser? I see that Megaparsec has [`dbg`](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec.html#g:7), but I'm not that familiar with monad transformers, so I'm not sure how to get this to play with `JournalParser` (my current approach is to try sticking a `lift` in at arbitrary places, but this has so far not worked ;))

**Comment by awjchen** [comment]
This parsing bug is my fault. Sorry for the trouble. The following diff seems to fix the problem when applied to the current master.

```
diff --git a/hledger-lib/Text/Megaparsec/Custom.hs b/hledger-lib/Text/Megaparsec/Custom.hs
index 5dce6f78..947cbb99 100644
--- a/hledger-lib/Text/Megaparsec/Custom.hs
+++ b/hledger-lib/Text/Megaparsec/Custom.hs
@@ -93,7 +93,11 @@ parseErrorAtRegion startPos endPos msg =
 
 withSource :: Text -> ParseError Char CustomErr -> ParseError Char CustomErr
 withSource s e =
-  FancyError (errorPos e) $ S.singleton $ ErrorCustom $ ErrorWithSource s e
+  FancyError (tail' (errorPos e)) $ S.singleton $ ErrorCustom $ ErrorWithSource s e
+  where
+    tail' xs = case snd (NE.uncons xs) of
+      Nothing -> xs
+      Just ys -> ys
 
 
 --- * Pretty-printing custom parse errors
```

As far as I understand, the bug occurred because
- raising a parse error in an include file causes backtracking due to the use of `choiceInState` in `includedirectivep`
- when backtracking occurs, there is the opportunity for multiple failures
- megaparsec must take these multiple failures and somehow merge them into a single failure
- if megaparsec is given two parse errors with different source positions, megaparsec will return the parse error with the 'longest match", that is, the one with largest source position (`SourcePos`)
- "largest" is determined by the `Ord` instance for `SourcePos`, which is derived, so it is a lexicographic ordering on its fields
- the first field is the filepath of the source file (!), so it dominates the ordering
- now, in my implementation of `withSource`, I have to create a new parse error, which requires a stack of source positions
- previously, I just used the stack of positions from the parse error raised in the include file as the stack  for the new error; the top of this stack is positioned within the _include_ file
- however, this is incorrect because the new error is being merged with other parse errors positioned within a different source file (that is, the _parent_ source file)
- so then, when megaparsec merges these errors, it basically selects which error to show by looking only at their filepaths (since the filepath dominates the ordering), causing the strange, asymmetric behaviour

**Comment by simonmichael** [comment]
I'm so glad it was you who chased this down. :) Very good, thanks! 👍 

It sounds like the above change would fix it, but can we do it in a more direct way by preventing backtracking here ?

**Comment by awjchen** [comment]
I agree that backtracking is an issue here, and that we need to eliminate it. The two options I see are (a) to modify the include file code so that it does not use backtracking, or (b) to reintroduce the `ExceptT` layer of the parser in order to throw parse errors without backtracking.

For (a), I think we would need some way to tell ahead of time whether the file should be a journal file, timeclock file, or timedot file. One backwards-compatible way to do this would be to add an optional annotation on include files indicating the "file type".

For (b), the main concern I had when suggesting its removal was maintaining consistency of parse error messages between two parse error mechanisms, but I no longer see why they need be consistent in their presentation. I don't know much at all about parsing, so I don't know whether it's better or easier to have non-backtracking parse errors. Though, at the moment, it still seems like we can generate good error messages by being careful with our use of backtracking.

**Comment by awjchen** [comment]
Also, I think my suggested diff to `withSource` is incorrect. If it were applied, the parser would throw away the position of the error in the child source file. But megaparsec needs this information to choose the error with the longest match when backtracking between `journalp`, `timeclockfilep`, and `timedotfilep`.

So, neither the original code nor the diff are correct. Now I'm thinking that that might be no way to get the behaviour we want with megaparsec.

I explained before that megaparsec examines the source positions of the errors when merging them, looking for the error with the largest position. To be more precise, megaparsec compares the stacks of source positions, but because of the ordering on `NonEmpty`, the source position at the top of the include stack dominates the ordering. Given the way we use the stack of source positions, more is true: the top source position completely determines the ordering, since the other source positions will be equal if the top source positions are. So, we effectively have only one source position to communicate to megaparsec an intended ordering, but it looks to me like no single position is sufficient.

I think that the behaviour we want would be implemented by the "reverse" ordering on the stack, where the bottom-most position of the stack is the most significant, but this code is internal to megaparsec.

**Comment by simonmichael** [comment]
We want backtracking sometimes, but we also want to be able to stop backtracking at will. It would be a pity to re-add the ExceptT layer to our parsers after removing it. I feel there must be something built in to megaparsec to escape backtracking, it is a very common need.

**Comment by simonmichael** [comment]
Does failure/fancyFailure do it ? http://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec.html#v:fancyFailure

**Comment by awjchen** [comment]
I don't think `failure` or `fancyFailure` would stop backtracking, since in `Text.Megaparsec.Internal` they look like they are doing basically the same thing as `fail`, which doesn't stop backtracking.

Perhaps re-adding the `ExceptT` layer is the way to go. It certainly gives us a lot of flexibility, and I wouldn't mind re-implementing it.

**Comment by simonmichael** [comment]
I couldn't quite see what they do ("eerr"). The docs certainly make it sound like these are for what we want to do.. The changelog suggests that failure is for "trivial" errors and fancyFailure is for "non-trivial" errors. We should make a little backtracking test we can experiment with.

**Comment by simonmichael** [comment]
Inquiry: https://github.com/mrkkrp/megaparsec/issues/315

**Comment by simonmichael** [comment]
@awjchen it looks like that feature is not yet in megaparsec. I guess our best option to restore confidence in our errors, for now, is to re-add the ExceptT layer as you say.

**Comment by simonmichael** [comment]
Unfortunately.

**Comment by awjchen** [comment]
Just wanted to let you know that I've started to work on moving hledger to megaparsec 7 and re-implementing the `ExceptT` layer. I'm thinking of tackling this issue first, before the stuff in #807. My reasoning is that, since megaparsec 7 no longer tracks the stack of source positions we use for include files, I have to work on the logic for include files, anyway.

**Comment by simonmichael** [comment]
Great news, thanks @awjchen.

**Comment by simonmichael** [comment]
This is complete now that we are getting the proper error. Thanks!
