### ISSUE TITLE
web add form can create unbalanced transactions

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#951]
Lately unbalanced transactions keep showing up at http://demo.hledger.org , which I assume are coming from the add form there. This should not be possible.

**Comment by simonmichael** [comment]
@zarybnicky, it feels like we lost a lot of validation in cc1241fa20, or am I just not seeing it ?

**Comment by simonmichael** [comment]
Oh there it is, in AddForm.hs. But I get the feeling it's not working.. might you have a chance to check it ?

**Comment by simonmichael** [comment]
To reproduce (not at demo.hledger.org please :) just add a transaction with both amounts positive.

**Comment by zarybnicky** [comment]
@simonmichael Looking over the code quickly: checking of the postings' shape now is more rigorous, but a call to `balanceTransaction Nothing etxn` fell out during the rewrite. The fix should be trivial, I'll try to open a pull request tomorrow.

**Comment by zarybnicky** [comment]
Pull request in progress - checking for a balanced transaction is trivial, but displaying the values on an 'unbalanced transaction' isn't - esp. with the weird posting validation algorithm...

I see that microlens is a transitive dependency, mind if I pull it in and use it to simplify postings validation so that it's actually readable without a half hour headache?

**Comment by simonmichael** [comment]
Thanks for looking at it. Sure, please go ahead. Displaying the error nicely will be great but even just preventing the write will be a win (so that hledger-web and hledger-api demos don't keep getting broken).
